name: EC2-instance-workflow
on:
  workflow_dispatch:
    inputs:
     ec2_name:
        description: "EC2 instance name"
        type: string
        required: true
        default: "My-Instace"
jobs:
  create-and-run:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout to repo
       uses: actions/checkout@v4

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "ap-south-1"
        

     - name: terraform-setup
       uses: hashicorp/setup-terraform@v3
       with: 
            terraform_version: "1.1.7"
      
     - name: Terraform Apply
       env:
           TF_VAR_ec2_name = ${{ github.event.inputs.ec2_name }}
       run: |
            cd infra/
            terraform init
            terraform validate
            terraform plan
            terraform apply --auto-approve     